/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.22 from the
 * contents of Helper.xs. Do not edit this file, edit Helper.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Helper.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

#include <sys/ioctl.h>
#include <fcntl.h>
#include <inttypes.h>
#include <linux/types.h>
#include <errno.h>
#include <linux/usb/ch9.h>
#include <linux/usbdevice_fs.h>

#include "wacom_ioctl.h"

#define ROWS 32
#define COLS 64

#define WACOM_SET_HANDEDNESS _IOW(0x00, 0x01, struct wacom_handedness)

int set_ring_led(char *usb_file, int btn)
{
        struct wacom_led_mode led_mode;
        struct usbdevfs_ioctl wrapper;
        int usb_fd;
        int r;

        usb_fd = open(usb_file, O_RDWR);
        if (usb_fd < 0)
                return -1;

        /* setup led data */
        led_mode.led_sel = 0x04+btn;
        led_mode.led_llv = 0x7f;
        led_mode.led_hlv = 0x7f;
        led_mode.oled_lum = 0x00;

        /* make syscall */
        wrapper.ifno = 0;
        wrapper.ioctl_code = WACOM_SET_LED_MODE;
        wrapper.data = &led_mode;

        r = ioctl(usb_fd, USBDEVFS_IOCTL, &wrapper);
        close(usb_fd);
        if (r < 0)
                return r;

        return EXIT_SUCCESS;
}

int set_image_led(char *usb_file, char *img, int btn)
{
        struct wacom_led_img led_img;
        struct usbdevfs_ioctl wrapper;
        int usb_fd;
        int r;

        usb_fd = open(usb_file, O_RDWR);
        if (usb_fd < 0)
                return -1;

        /* setup led data */
        memcpy(led_img.buf, img, ROWS*COLS);
        led_img.btn = btn;

        /* make syscall */
        wrapper.ifno = 0;
        wrapper.ioctl_code = WACOM_SET_LED_IMG;
        wrapper.data = &led_img;

        r = ioctl(usb_fd, USBDEVFS_IOCTL, &wrapper);
        close(usb_fd);
        if (r < 0)
                return r;

        return EXIT_SUCCESS;
}

int set_left_handed(char *usb_file, int left_handed)
{
        struct wacom_handedness handedness;
        struct usbdevfs_ioctl wrapper;
        int usb_fd;
        int r;

        usb_fd = open(usb_file, O_RDWR);
        if (usb_fd < 0)
                return -1;

        /* setup led data */
        handedness.left_handed = left_handed;

        /* make syscall */
        wrapper.ifno = 0;
        wrapper.ioctl_code = WACOM_SET_HANDEDNESS;
        wrapper.data = &handedness;

        r = ioctl(usb_fd, USBDEVFS_IOCTL, &wrapper);
        close(usb_fd);
        if (r < 0)
                return r;

        return EXIT_SUCCESS;
}

#line 123 "Helper.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 175 "Helper.c"

XS(XS_Wacom__Helper_set_ring_led); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wacom__Helper_set_ring_led)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "usb_file, btn");
    {
	char*	usb_file = (char *)SvPV_nolen(ST(0));
	int	btn = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = set_ring_led(usb_file, btn);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Wacom__Helper_set_image_led); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wacom__Helper_set_image_led)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "usb_file, img, btn");
    {
	char*	usb_file = (char *)SvPV_nolen(ST(0));
	char*	img = (char *)SvPV_nolen(ST(1));
	int	btn = (int)SvIV(ST(2));
	int	RETVAL;
	dXSTARG;

	RETVAL = set_image_led(usb_file, img, btn);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Wacom__Helper_set_left_handed); /* prototype to pass -Wmissing-prototypes */
XS(XS_Wacom__Helper_set_left_handed)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "usb_file, left_handed");
    {
	char*	usb_file = (char *)SvPV_nolen(ST(0));
	int	left_handed = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = set_left_handed(usb_file, left_handed);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Wacom__Helper); /* prototype to pass -Wmissing-prototypes */
XS(boot_Wacom__Helper)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Wacom::Helper::set_ring_led", XS_Wacom__Helper_set_ring_led, file);
        newXS("Wacom::Helper::set_image_led", XS_Wacom__Helper_set_image_led, file);
        newXS("Wacom::Helper::set_left_handed", XS_Wacom__Helper_set_left_handed, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

